# Use root/example as user/password credentials
version: '3.8'
services:
  app:
    container_name: api
    build: .
    depends_on:
      - db
    links:
      - db
    expose:
      - "5000"
    ports:
      - "5000:5000"
    networks:
      - python-network
  db:
    container_name: MYSQL
    hostname: mysql-db
    image: mysql:8.0.21
    ports:
      - "3000:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: asistenciaec
    volumes:
      - ./db:/app/db
    networks:
      - python-network


networks:
  python-network:
    name: python-network
    # driver: bridge
